### ISSUE TITLE
Using `set` as an arm name for SCSpecTypeDef breaks the js-xdr package.

### ISSUE THREAD

**Issue by wildework** [stellar/stellar-xdr#72]
### What version are you using?

The latest commit on `next`, `df18148747e807618acf4639db41c4fd6f0be9fc`.

### What did you do?

I generate the JavaScript version of XDR using `xdrgen` which imports `js-xdr`. Because `js-xdr` uses the keyword `set` when it tries to interact with `SCSpecTypeDef` it breaks.

```
union.js:65 Uncaught (in promise) Error: set not set
    at ChildUnion2.get (union.js:65:15)
    at ChildUnion2.get [as set] (union.js:219:23)
    at ChildUnion2.Union2 (union.js:44:10)
    at new ChildUnion2 (union.js:146:111)
    at Function.read (union.js:120:14)
    at var-array.js:60:33
    at baseTimes (_baseTimes.js:15:21)
    at times (times.js:44:16)
    at VarArray2.read (var-array.js:59:26)
    at struct.js:57:26
```

### What did you expect to see?

No errors when using `js-xdr` with the latest XDR.

### What did you see instead?

The `set not set` error.

We can fix this by simply uppercasing the `set` to `Set`, or picking another name.

**Comment by leighmcculloch** [comment]
How we normally address name issues like this is by having xdrgen rename the field. For example, in the Rust generator any field named `type` is problematic, and so instead it names them `type_`. We can same for the set case.
